### ISSUE TITLE
not showing on admin UI

### ISSUE THREAD

**Issue by mamged** [outgrow/reaction-marketplace-ui#1]
Hi @loan-laux 
I'm trying to install this plugin, I did every step and it still not showing on admin UI.
Kindly note that the installed [reaction-platform](https://github.com/reactioncommerce/reaction-development-platform) version is the latest
This is the log
```> reaction-admin@3.0.0-beta.7 start:dev /Users/m/mylab/reaction-marketplace/reaction-admin
> node --experimental-modules ./.reaction/scripts/run.mjs

(node:34225) ExperimentalWarning: The ESM module loader is experimental.
Setting up plugin imports...

Installing dependencies for reaction-marketplace-ui...

npm WARN mdi-material-ui@6.19.0 requires a peer of @material-ui/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mdi-material-ui@6.19.0 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN reaction-marketplace-ui@0.1.0 No repository field.

audited 1 package in 1.723s
found 0 vulnerabilities

Setting up plugin imports took 3s 125.294565ms

Setting up style imports...

Setting up style imports took 0s 15.996452ms

Provisioning assets...

Provisioning assets took 0s 14.259708ms

Running command: meteor run --port 4080 --no-lint --no-release-check --raw-logs
[[[[[ ~/mylab/reaction-marketplace/reaction-admin ]]]]]

=> Started proxy.
app/client/plugins.less: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
app/client/plugins.less: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
16:14:36.397Z  INFO Reaction: Meteor startup finished: 169501ms (This is incorrect if this is a restart.)
16:14:36.399Z  INFO Reaction: Waiting for Hydra service to be available...
16:14:36.423Z  INFO Reaction: Hydra service is available.
16:14:36.693Z  INFO Reaction: Updating Hydra client...
16:14:36.760Z  INFO Reaction: OK: Hydra client updated
16:14:36.760Z  INFO Reaction: Reaction initialization finished: 363ms
=> Started your app.

=> App running at: http://localhost:4080
```

**Comment by mamged** [comment]
@loan-laux is there certain version of reaction that needed to make this plugin work?

**Comment by loan-laux** [comment]
@mAmged This plugin has been kind of on hold for now while I was focusing on implementing the new shop selector on `reaction-admin`. You can check it out on master, and an official beta release is coming soon too. In the next few days, I'll pick up this plugin again and things will be a lot easier to implement now that there's actual multi-shop support on `reaction-admin`.

**Comment by mamged** [comment]
@loan-laux when u developed this plugin, which version it was working?

**Comment by loan-laux** [comment]
@mAmged I think it was about 3.7 or something, but don't expect to use this plugin to do anything for now. It's really basic and not very useful as it stands. The goal was to prepare RC with the things I needed to build this plugin, and then get back to it when that was done.

**Comment by mamged** [comment]
@loan-laux is there branch that someone is working on currently to implement this RC so I can jump with to get this done?

**Comment by loan-laux** [comment]
Unfortunately not @mAmged, but keep an eye on this repo for updates soon!

**Comment by avidsapp** [comment]
Any movement on this?

**Comment by loan-laux** [comment]
@avidsapp is the plugin not showing in the sidebar for you?

**Comment by avidsapp** [comment]
Correct, not showing

**Comment by loan-laux** [comment]
@avidsapp are you logged in with a user that's part of the `owner` group? The plugin will only appear in the sidebar when you are an owner.

**Comment by avidsapp** [comment]
Yes, I'm logged in as an owner and shop manager
